### ISSUE TITLE
Need better example

### ISSUE THREAD

**Issue by smousa** [mblarsen/browser-acl#5]
I cannot seem to set rules from a class type (`can` always returns false):

```js
import Vue from 'vue'
import Acl from 'vue-browser-acl'

class Organization {
  beforeAll (verb, user, org) {
    if (!user.isLoggedIn()) {
      return false
    }
    if (user.ownerOf(org.id)) {
      return true
    }
  }

  view (user, org) {
    return user.memberOf(org.id)
  }
}

Vue.use(Acl, user, (acl) => {
  acl.subjectMapper = s => typeof s === 'string' ? s : s.type
  acl.register(Organization, 'Organization')
  acl.rule('view', Organization)
})
```
What am I doing wrong?

The only way the rule works is if I do something like:
`acl.rule('view', 'Organization', (user, org) => user.memberOf(org.id))`

**Comment by smousa** [comment]
I figured it out:

The `Organization` in the example above should be registered as a `policy`

```js
import Vue from 'vue'
import Acl from 'vue-browser-acl'

class OrganizationPolicy {
  beforeAll (verb, user, org) {
    if (!user.isLoggedIn()) {
      return false
    }
    if (user.ownerOf(org.id)) {
      return true
    }
  }

  view (user, org) {
    return user.memberOf(org.id)
  }
}

Vue.use(Acl, user, (acl) => {
  acl.subjectMapper = s => typeof s === 'string' ? s : s.type
  acl.policy(OrganizationPolicy, 'Organization')
})
```

I know that you put this in your fiddle, but it would be helpful if you would clarify this in the README

**Comment by mblarsen** [comment]
Maybe the issue is that if you are not familiar with Laravel (which is the inspiration) then it isn't clear that classes are 'policies'.

`.register` is for ensuring that your class instances of your models will work after minification. `.policy` is basically the same as `.rule` except for the rule name you pass in the policy object or class.

```diff
Vue.use(Acl, user, (acl) => {
- acl.subjectMapper = s => typeof s === 'string' ? s : s.type
+ acl.register(Organization, 'Organization')
- acl.policy(OrganizationPolicy, 'Organization')
+ acl.policy(OrganizationPolicy, Organization)
})
```
(this assumes that you have a `Organization` class)

Anyway, do you suggest putting it in the setup section of the [README setup section](https://github.com/mblarsen/browser-acl#setup):

---

Policies are also supported:

```diff
+ // using an object
  acl.policy({
    view: true,
    edit: (user, post) => post.userId === user.id),
  }, Post)

+ // or a class
+ acl.policy(OrganizationPolicy, Organization)
```

Note: policies takes precedence over rules.

**Comment by smousa** [comment]
Yes, I am unfamiliar with Laravel, and I missed that `Post` in your example was not the same as `PostPolicy`

I think that an example of how a policy is registered would be most helpful :)
